version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "8081:80"
    volumes:
      - ./docker/configs/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    restart: unless-stopped
